---
# file: roles/app/tasks/main.yml
# usage:
# ansible-playbook app.yaml -e "SOURCE=TAG TAG=release_123"

  ### Stop Hybris ###
  - name: (deploy) stop hybris
    command: /etc/init.d/hybris stop
    tags:
      - hybris-stop

  ### git fetch latest ###
  - name: (deploy) git fetch
    command: git fetch chdir=/opt/hybris

  - name: (deploy) git fetch tags
    command: git fetch --tags chdir=/opt/hybris

  ### git checkout master ###
  - name: (deploy) git checkout master
    command: git checkout master chdir=/opt/hybris

  ### delete all old branches ###
  - name: (deploy) delete old branches
    shell: git branch | grep -v "master$" | xargs git branch -D chdir=/opt/hybris

  ### if TAG, then: ###
  - name: (current) git checkout new tag
    command: git checkout -b {{ TAG }}_local tags/{{ TAG }} chdir=/opt/hybris
    when: SOURCE == "TAG" and TAG is defined

  ### if BRANCH, then: ###
  - name: (branch) git checkout new branch
    command: git checkout -b {{ BRANCH }}_local origin/{{ BRANCH }} chdir=/opt/hybris
    when: SOURCE == "BRANCH" and BRANCH is defined

  ### run puppet to get config changes to local.properties ###
  - name: (deploy) puppet run
    # puppet can not use '--detailed-exitcodes' since the exit codes will cause ansible to fail
    raw: sudo puppet agent -v --onetime --verbose --ignorecache --no-daemonize --no-usecacheonfailure --no-splay --show_diff
    sudo: yes
    sudo_user: admin

  - name: (deploy) ant setup
    raw: cd /opt/hybris/bin/platform && source ./setantenv.sh

  - name: (deploy) ant clean all
    command: "{{ ANT_BIN }} clean all chdir=/opt/hybris/bin/platform"

  - name: (deploy) start hybris
    command: /etc/init.d/hybris start
    tags:
      - hybris-start

  ### sync _ui folder from backend server after ant build ###
  - include: images.yml
    when: facter_env == "prd" or facter_env == "sta"
